// .agents/skills/experience-cms-content-render/assets/react/TypeRenderer.tsx
/**
 * {{Type}}Renderer — per-type wrapper (codegen-managed; regenerated on schema sync).
 * No user region — customize via {{type}}Layouts/{{type}}Slots in `./{{type}}.ts`.
 * Delegates ALL field rendering to heuristicRenderer — do NOT inject HTML here
 * (Rule 4). `ref` is typed `AnyCmsRef<'{{type}}'>` — a ref whose `cmsType` differs is
 * a compile error. Fields are read directly, never `.value` (Rule 5).
 * Tokens: {{Type}} PascalCase, {{type}} camelCase.
 */
import type { ReactNode, ComponentType } from 'react';
import type { AnyCmsRef } from '../../shared/cmsCore.types';
import { useCmsItem } from '../useCmsItem';
import { heuristicRenderer } from '../heuristicRenderer';
import { {{type}}Layouts, {{type}}Slots, type {{Type}}Body, type {{Type}}Layout } from './{{type}}';

export interface {{Type}}RendererProps {
  ref: AnyCmsRef<'{{type}}'>;
  layout?: {{Type}}Layout;
  /** Whitelist of {{Type}}Body field names. Bypasses layout's default field list. */
  fields?: ReadonlyArray<keyof {{Type}}Body & string>;
  components?: {
    Title?: ComponentType<{ value: string }>;
    Image?: ComponentType<{ src: string; alt?: string }>;
    RichText?: ComponentType<{ html: string }>;
  };
  className?: string;
}

export function {{Type}}Renderer(props: {{Type}}RendererProps): ReactNode {
  const {
    ref,
    layout = 'card',
    fields,
    components,
    className,
  } = props;

  const { body, loading, error } = useCmsItem<{{Type}}Body>(ref);

  // fields: per-embed prop → layout preset → undefined (heuristic mode).
  const layoutPreset = {{type}}Layouts[layout];
  const resolvedFields = fields ?? layoutPreset.fields;

  // components: per-embed prop → type-level slot defaults.
  const resolvedComponents = {
    ...(( {{type}}Slots as unknown) as {{Type}}RendererProps['components']),
    ...components,
  };

  const resolvedClassName = className ?? layoutPreset.className;

  // 'detail' layout key routes to detail-mode rendering; every other custom
  // layout falls through to list-mode. Add more layouts in `{{type}}.ts`.
  const rendererLayout = layout === 'detail' ? 'detail' : 'list';

  return heuristicRenderer({
    body: body as Record<string, unknown> | undefined,
    loading,
    error,
    layout: rendererLayout,
    fields: resolvedFields as ReadonlyArray<string> | undefined,
    components: resolvedComponents,
    className: resolvedClassName,
  });
}

// .agents/skills/experience-cms-content-render/assets/angular/TypeRenderer.component.ts
/**
 * {{Type}}RendererComponent — per-type wrapper for Angular (codegen-managed;
 * regenerated on schema sync). Counterpart of React's {{Type}}Renderer. No user
 * region — customize via {{type}}Layouts/{{type}}Slots in
 * `src/cms/angular/types/{{type}}.ts`.
 *
 * SMART container: injects CmsItemService, loads the ref, hands the body to the DUMB
 * `<cms-content>` where all rendering (incl. the one RichText path) lives — do NOT
 * inject HTML here (Rule 4); never unwrap `.value` (Rule 5). `ref` is typed
 * `AnyCmsRef<'{{type}}'>` — a ref whose `cmsType` differs is a compile error.
 * Tokens: {{Type}} PascalCase, {{type}} camelCase.
 */
import { Component, Input, type OnChanges, signal } from '@angular/core';
import { CmsContentComponent } from '../cms-content.component';
import { CmsItemService } from '../cms-item.service';
import type { AnyCmsRef } from '../../shared/cmsCore.types';
import { {{type}}Layouts, type {{Type}}Body, type {{Type}}Layout } from './{{type}}';

@Component({
  selector: 'cms-{{type}}',
  standalone: true,
  imports: [CmsContentComponent],
  template: `
    <cms-content
      [body]="body()"
      [loading]="loading()"
      [error]="error()"
      [layout]="rendererLayout"
      [fields]="resolvedFields"
      [className]="resolvedClassName"
    ></cms-content>
  `,
})
export class {{Type}}RendererComponent implements OnChanges {
  @Input({ required: true }) ref!: AnyCmsRef<'{{type}}'>;
  @Input() layout: {{Type}}Layout = 'card';
  /** Whitelist of {{Type}}Body field names. Bypasses the layout's default field list. */
  @Input() fields?: ReadonlyArray<keyof {{Type}}Body & string>;
  @Input() className?: string;

  readonly body = signal<{{Type}}Body | undefined>(undefined);
  readonly loading = signal(true);
  readonly error = signal<Error | undefined>(undefined);

  // Name of the ref the signals currently describe. Lets ngOnChanges tell a ref
  // switch (clear + reload) apart from a same-ref prop change (layout/fields).
  private loadedRefName?: string;

  // 'detail' layout key routes to detail-mode rendering; every other custom
  // layout falls through to list-mode. Add more layouts in `{{type}}.ts`.
  get rendererLayout(): 'list' | 'detail' {
    return this.layout === 'detail' ? 'detail' : 'list';
  }

  // Resolution order for `fields`: per-embed prop → layout preset → undefined
  // (heuristic mode). Cast mirrors the React renderer's ReadonlyArray<string>.
  get resolvedFields(): ReadonlyArray<string> | undefined {
    return (this.fields ?? {{type}}Layouts[this.layout].fields) as
      | ReadonlyArray<string>
      | undefined;
  }

  get resolvedClassName(): string {
    return this.className ?? {{type}}Layouts[this.layout].className;
  }

  constructor(private readonly cms: CmsItemService) {}

  ngOnChanges(): void {
    const ref = this.ref;
    // Only (re)load when the ref identity changes — a layout/fields-only change
    // must not drop the already-resolved body back into a loading state.
    if (ref.name === this.loadedRefName) return;
    this.loadedRefName = ref.name;

    // Ref switched: drop the previous item's body/error so its content can't stay
    // visible under the new ref, and show loading until this ref resolves. The
    // service dedups by ref.name, so a shared ref reuses the in-flight/cached result.
    this.body.set(undefined);
    this.error.set(undefined);
    this.loading.set(true);
    void this.cms.load<{{Type}}Body>(ref).then((result) => {
      // Ignore a stale resolution if the ref changed while this was in flight.
      if (this.ref !== ref) return;
      this.body.set(result.body);
      this.error.set(result.error);
      this.loading.set(false);
    });
  }
}
